name: fpm test

on: [push, pull_request]

jobs:
  gfortran:
    runs-on: ubuntu-latest

    env:
      FC: gfortran
      GCC_V: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install prerequisites
      run: |
        sudo apt-get install libhdf5-dev libcurl4-openssl-dev --yes

    # - name: Install ifort from cache
    #   id: cache-netcdf
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       /opt/intel/oneapi/compiler
    #       /opt/intel/oneapi/setvars.sh
    #     key: oneapi-cache-v0

    - name: Install netcdf-c
      run: |
        cd /tmp
        git clone https://github.com/Unidata/netcdf-c.git
        cd netcdf-c
        mkdir build; cd build
        cmake ..
        make -j
        sudo make install

    - name: Install netcdf-fortran
      run: |
        cd /tmp
        git clone https://github.com/Unidata/netcdf-fortran.git
        cd netcdf-fortran
        mkdir build; cd build
        cmake ..
        make -j
        sudo make install
        sudo ldconfig

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests and demo programs (debug)
      run: |
        gfortran --version
        fpm test

    - name: Run tests and demo programs (release)
      run: |
        gfortran --version
        fpm test --profile release
